[env:ESP32-DIV-v2]
board = ESP32-DIV-v2
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ESP32-DIV-v2>
build_flags =
	${env.build_flags}
	-Iboards/ESP32-DIV-v2
	-Os
	-DCORE_DEBUG_LEVEL=1
	-DREDRAW_DELAY=1
	-DALLOW_ALL_GPIO_FOR_IR_RF=1
	-DDISABLE_ALL_LIBRARY_WARNINGS

	; Screen Setup
	-DHAS_SCREEN=1
	-DROTATION=2
	-DMINBRIGHT=20

	-DUSER_SETUP_LOADED=1
	-DILI9341_DRIVER=1
	-DUSE_HSPI_PORT=1
	-DTFT_HEIGHT=320
	-DTFT_WIDTH=240
	-DTFT_MISO=37
	-DTFT_MOSI=35
	-DTFT_SCLK=36
	-DTFT_CS=17
	-DTFT_DC=16
	-DTFT_RST=0
	-DTFT_BL=7
	-DTFT_BACKLIGHT_ON=HIGH
	-DSMOOTH_FONT=1
	-DSPI_FREQUENCY=27000000
	-DSPI_READ_FREQUENCY=20000000
	
	; tft Brightness Control
	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=5000

	; SPI touchscreen controller XPT2046
	-DHAS_TOUCH=1
	-DUSE_TFT_eSPI_TOUCH=1
	-DTOUCH_CS=18
	-DSPI_TOUCH_FREQUENCY=2500000

	; SD Card Setup (SPI mode)
	-DSDCARD_CS=10
	-DSDCARD_MOSI=11
	-DSDCARD_MISO=13
	-DSDCARD_SCK=12

	; Default I2C port (for PCF8574 buttons)
	-DGROVE_SDA=8
	-DGROVE_SCL=9

	; SPI Pin definitions for status screens
	-DSPI_SCK_PIN=12
	-DSPI_MOSI_PIN=11
	-DSPI_MISO_PIN=13
	-DSPI_SS_PIN=5

	; BadUSB Serial Pins
	-DBAD_TX=GROVE_SDA
	-DBAD_RX=GROVE_SCL

	; NRF24 configuration
	-DUSE_NRF24_VIA_SPI=1
	-DNRF24_CE_PIN=15
	-DNRF24_SS_PIN=4
	-DNRF24_MOSI_PIN=11
	-DNRF24_SCK_PIN=12
	-DNRF24_MISO_PIN=13

	; CC1101 SPI configuration
	-DUSE_CC1101_VIA_SPI=1
	-DCC1101_GDO0_PIN=6
	-DCC1101_GDO2_PIN=3
	-DCC1101_SS_PIN=5
	-DCC1101_MOSI_PIN=11
	-DCC1101_SCK_PIN=12
	-DCC1101_MISO_PIN=13

	; GPS Serial Configuration (Disabled)
	-DGPS_SERIAL_TX=-1
	-DGPS_SERIAL_RX=-1
	-DSERIAL_RX=-1
	-DSERIAL_TX=-1

	; IR Configuration
	-DRXLED=-1
	-DIR_TX_PINS='{{"Pin 14", 14}}'
	-DIR_RX_PINS='{}'
	-DTXLED=14
	-DLED_ON=HIGH
	-DLED_OFF=LOW

	; Battery ADC
	-DBAT_PIN=-1
	-DBUZZ_PIN=2

	-DDEVICE_NAME='"ESP32-DIV-v2"'

lib_deps =
	${env.lib_deps}
	xreef/PCF8574 library @ ^2.4.0
